### ISSUE TITLE
Wrong version? flathub says 0.2.3 but it's version 0.23

### ISSUE THREAD

**Issue by 1player** [flathub/io.webtorrent.WebTorrent#13]
Perhaps the bug is here:

https://github.com/flathub/io.webtorrent.WebTorrent/blob/3209ac50e33ce8f3cf5d6a633bc6387eaf7d8640/io.webtorrent.WebTorrent.metainfo.xml#L26

**Comment by bilelmoussaoui** [comment]
Probably, feel free to send a patch
